# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 002a90c548b89f89cdfbeef05fdf7a34b58d98b6f174d09cdad1a498823ee0cecd6c485a64367f8042a4ae61a04cb3075b0ee09046b5cd7bef39c6f148180c38

test:
  secret_key_base: c94c544423bd2088af9c8a4cba50f9a06c09c78f7f13975499bf96bc8f90f399b70dc4aa1dee6405d7aec745dbff18ab1688d8a21df58019971905693366a26b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
